{% set name = "fastparquet" %}
{% set version = "0.1.1" %}
{% set fn_suffix = "0.1.1.tar.gz" %}
{% set sha256 = "189105b53f56b5ed4d9077a0b22de0055b79917ae9a083dfb7abe9453d754d28" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ fn_suffix }}
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ fn_suffix }}
  sha256: "{{ sha256 }}"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - pandas
    - numpy
    - numba
    - thriftpy
    - pytest
    - cython

test:
  imports:
    - fastparquet

about:
  home: http://github.com/martindurant/fastparquet
  license: BSD-3
  license_family: 'BSD'
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/martindurant/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin 
