{% set name = "fastparquet" %}
{% set version = "0.3.1" %}
{% set sha256 = "f18f22ba31cb54efff00980f53d4a77b4027bbdb0a5cf1c4644113551196c0f0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version  }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  build:
    - python
    - pip 
    - setuptools
    - cython
    - numpy
    - pytest-runner
    - numba
    - thrift
    - {{ pin_compatible('numpy') }}
  host:
    - {{ compiler('c') }}
    - python
    - pip
    - setuptools
    - numpy
    - pytest-runner
    - numba
    - thrift
  run:
    - python
    - pandas >=0.19
    - numpy >=1.11
    - numba >=0.28
    - thrift 0.11.*
    - pytest

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3
  license_family: 'BSD'
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
