{% set name = "fastparquet" %}
{% set version = "2024.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dffd1d0ac6e89e31c5b6dacf67a8d299d4afbbcf0bf8b797373904c819c48f51

build:
  skip: true  # [py<38]
  number: 0
  script:
    - del fastparquet\*.c  # [win]      
    - rm fastparquet/*.c   # [unix]    
    - {{ PYTHON }} {{ RECIPE_DIR }}/un_oldest.py
    - '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython <3
    - pandas
    - pip
    - setuptools
    - setuptools-scm >1.5.4
    - numpy
    - pytest-runner
    - packaging
  run:
    - python
    - pandas >=1.5.0
    - numpy >=1.20.3
    - {{ pin_compatible('numpy') }}
    - cramjam >=2.3
    - fsspec
    - packaging

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python interface to the parquet format
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
