{% set name = "fastparquet" %}
{% set version = "0.7.2" %}
{% set sha256 = "3c4bd638260357df55a9e71d0bd797c12f14f691a61dfd91a66f5b8d2a247683" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - del fastparquet\*.c  # [win]      
    - rm fastparquet/*.c   # [unix]    
    - {{ PYTHON }} {{ RECIPE_DIR }}/un_oldest.py
    - '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pandas
    - pip
    - setuptools
    - numpy
    - pytest-runner
    - packaging
    - thrift >=0.11
  run:
    - python
    - pandas >=1.0.0
    - {{ pin_compatible('numpy') }}
    - thrift >=0.11
    - cramjam >=2.3.0
    - fsspec

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python interface to the parquet format
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
