{% set name = "fastparquet" %}
{% set version = "0.2.1" %}
{% set fn_suffix = "0.1.6.tar.gz" %}
{% set sha256 = "f820626401f59037048a2472fc2f325d0193de3290fd48c012436d7b3a026d14" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ fn_suffix }}
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ fn_suffix }}
  sha256: "{{ sha256 }}"

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - pytest-runner
  run:
    - python
    - pandas >=0.19
    - numpy >=1.11
    - numba >=0.28
    - thrift 0.11.*
    - pytest

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3
  license_family: 'BSD'
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin 
