{% set name = "fastparquet" %}
{% set version = "0.8.2" %}
{% set sha256 = "7f54bb4718b6b360d8c864060b9bab88fd675709d5f3d8bae335aece9cb7fd53" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - del fastparquet\*.c  # [win]      
    - rm fastparquet/*.c   # [unix]    
    - {{ PYTHON }} {{ RECIPE_DIR }}/un_oldest.py
    - '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pandas
    - pip
    - setuptools
    - numpy
    - pytest-runner
    - packaging
  run:
    - python >=3.7
    - pandas >=1.0.0
    - {{ pin_compatible('numpy') }}
    - cramjam >=2.3.0
    - fsspec
    - packaging

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python interface to the parquet format
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
