{% set name = "fastparquet" %}
{% set version = "2024.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3b1fc73fd3e1b70b0de254bae7feb890436cb67e99458b88cb9bd3cc44db419

build:
  skip: true  # [py<39]
  number: 0
  script:
    - del fastparquet\*.c  # [win]      
    - rm fastparquet/*.c   # [unix]    
    - {{ PYTHON }} {{ RECIPE_DIR }}/un_oldest.py
    - '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.23                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.23
    - pandas
    - pip
    - setuptools
    - setuptools-scm >1.5.4
    - numpy
    - pytest-runner
    - packaging
  run:
    - python
    - pandas >=1.5.0
    - numpy
    - cramjam >=2.3
    - fsspec
    - packaging

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python interface to the parquet format
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
