{% set name = "fastparquet" %}
{% set version = "0.5.0" %}
{% set sha256 = "3b558059327dce2c73a775aa2f2029e052fcf6e61880e15681e04ede5f0f20b7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - del fastparquet\*.c  # [win]      
    - rm fastparquet/*.c   # [unix]      
    - '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pandas
    - pip
    - setuptools
    - numpy
    - pytest-runner
    - numba
    - packaging
    - thrift >=0.11
  run:
    - python
    - pandas >=0.19
    - numpy
    - packaging
    - numba >=0.28
    - thrift >=0.11

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python interface to the parquet format
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
