{% set name = "fastparquet" %}
{% set version = "0.0.5" %}
{% set fn_suffix = "0.0.5.tar.gz" %}
{% set sha256 = "38d003fda383f7d90005011e926a75909c9d804a31c7fc943600d25c1b5762c3" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ fn_suffix }}
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ fn_suffix }}
  sha256: "{{ sha256 }}"

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - pandas
    - numpy
    - numba
    - thriftpy
    - pytest
    - cython

test:
  imports:
    - fastparquet

about:
  home: http://github.com/martindurant/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/martindurant/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin 
