{% set name = "fastparquet" %}
{% set version = "0.0.4post1" %}
{% set fn_suffix = "0.0.4.post1.tar.gz" %}
{% set sha256 = "3f8e6c21bd26bdb41800e9408fe7560e040d4416e16a1b45b46f61a41d0c2665" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ fn_suffix }}
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ fn_suffix }}
  sha256: "{{ sha256 }}"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - numpy
    - numba
    - thriftpy
    - pytest

test:
  imports:
    - fastparquet

about:
  home: http://github.com/martindurant/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/martindurant/fastparquet

extra:
  recipe-maintainers:
    - martindurant
