appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dGlpqSWomrbf2/Zq+j1/rlU4XgOl8+OqH5g8sT5MXQJBn+Au27gxcVrxNBbzznUawTJigFwwWiDct+igU8iTYh6wDZSYtFPYx/qYNHfD7XHTGi/2EH2Z++95vS7DJN5Ig7UXPKLXB2NL0cM+5wgoXAgqmBgzawZi86MdzBzo5t6UJ4wO2bMJFzPb9PIf1H1wiafgwwpPOVon0irUq/h2+7cvXFNWY8Np8WQh0JxbwC1yrlkuZkqEo1bte/dmiRJn9jA4lhgesUM080i7YGODeaP5NrE6JsI5EGXV2IyGmFQRQacGGZSaJ2qMVdaCeY5O+X+VWTDw3v49tLMJm5zCFnPAsBKG8Nw83KXZStD3aPM4q8ICnqDvhL0Ub8d5qsJym+p2zFDMGHCAqOOPKV9LYafqHa53AL6ko1vjFMvxrEGEcDDOslA7v1Lf/q8HSmyoY2xelj1YaU5tojYRPmaZ5B0WE5DxHfpRpzS1NbGXJtfL/R+c1Fk+LL4C1BQ1bgq+QXZXSAeQWU9BSW03oO0cv3XtnM/rQK+ku+DewJzKZf84Fas91ja6fab+lBql0z0hWgWOyvzAQ7vwvbd+BFZw7s91Wcz5O/qSi00vZ0PeoGCxKKzrbdeZHzD7+bk8QxG0QpeUI9CuYLPXEX/gmnhycWNKo6iJ9g8+8axpHALh8U8=}
provider:
  win: azure
